version: "3"

services:
  webserver:
    build: .
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - .:/var/www/html/math.ru
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./vhosts:/etc/apache2/sites-enabled
      - ./logs:/logs/apache2/var/log/apache2
    environment:
      MODE: 'production'
      DB_SERVER: 'mysql'
      DB_NAME: 'math'
      DB_USER: 'math'
      DB_PASS: 'math'
      DB_USERTABLE: 'user'
      DEBUG: 'TRUE'
  mysql:
    image: mysql
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'math'
      MYSQL_USER: 'math'
      MYSQL_PASSWORD: 'math'
    command: --innodb-use-native-aio=0