version: "3"

services:
  webserver:
    build: 
      context: ./webserver
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ../:/var/www/html/math.ru
      - ./webserver/php/php.ini:/usr/local/etc/php/php.ini
      - ./webserver/vhosts:/etc/apache2/sites-enabled
      - .logs:/logs/apache2/var/log/apache2
    environment:
      MODE: 'production'
      DB_SERVER: 'mysql'
      DB_NAME: 'math'
      DB_USER: 'math'
      DB_PASS: 'password'
      DB_USERTABLE: 'user'
      DEBUG: 'TRUE'
  mysql:
    build: ./mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - .data/mysql:/var/lib/mysql
      - .logs/mysql:/var/log/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'localhost'
      MYSQL_DATABASE: 'math'
      MYSQL_USER: 'math'
      MYSQL_PASSWORD: 'password'
    command: --innodb-use-native-aio=0